config/routes.rb
Rails.application.routes.draw do
  resources :places
  devise_for :users
  resources :criminals 
  root to: "criminals#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/criminal.rb
class Criminal < ApplicationRecord
	has_attached_file :avatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
  	validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	geocoded_by :address   # can also be an IP address
	after_validation :geocode          # auto-fetch coordinates
	
	validates :first_name, length: { maximum: 15 }
	validates :second_name, length: { maximum: 15}
	validates_presence_of :height,:weight,:first_name,:second_name,:identification_mark,:location_of_crime,:address,:description,:age
  	validates :gender, :inclusion => { :in => %w(Male Female male female MALE FEMALE) }
end

app/models/place.rb
class Place < ApplicationRecord
	geocoded_by :address
	after_validation :geocode, if: :address_changed?
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/criminals_controller.rb
class CriminalsController < ApplicationController
  before_action :set_criminal, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit , :update, :destroy , :new , :create]
  # GET /criminals
  # GET /criminals.json
  def index
    @criminals = Criminal.all
  end

  # GET /criminals/1
  # GET /criminals/1.json
  def show
  end

  # GET /criminals/new
  def new
    @criminal = Criminal.new
  end

  # GET /criminals/1/edit
  def edit
  end

  # POST /criminals
  # POST /criminals.json
  def create
    @criminal = Criminal.new(criminal_params)

    respond_to do |format|
      if @criminal.save
        format.html { redirect_to @criminal, notice: 'Criminal was successfully created.' }
        format.json { render :show, status: :created, location: @criminal }
      else
        format.html { render :new }
        format.json { render json: @criminal.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /criminals/1
  # PATCH/PUT /criminals/1.json
  def update
    respond_to do |format|
      if @criminal.update(criminal_params)
        format.html { redirect_to @criminal, notice: 'Criminal was successfully updated.' }
        format.json { render :show, status: :ok, location: @criminal }
      else
        format.html { render :edit }
        format.json { render json: @criminal.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /criminals/1
  # DELETE /criminals/1.json
  def destroy
    @criminal.destroy
    respond_to do |format|
      format.html { redirect_to criminals_url, notice: 'Criminal was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_criminal
      @criminal = Criminal.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def criminal_params
      params.require(:criminal).permit(:first_name, :second_name, :identification_mark, :location_of_crime, :address, :height, :weight, :description, :gender, :age, :avatar)
    end
end

app/controllers/places_controller.rb
class PlacesController < ApplicationController
  before_action :set_place, only: [:show, :edit, :update, :destroy]

  # GET /places
  # GET /places.json
  def index
    @places = Place.all
  end

  # GET /places/1
  # GET /places/1.json
  def show
  end

  # GET /places/new
  def new
    @place = Place.new
  end

  # GET /places/1/edit
  def edit
  end

  # POST /places
  # POST /places.json
  def create
    @place = Place.new(place_params)

    respond_to do |format|
      if @place.save
        format.html { redirect_to @place, notice: 'Place was successfully created.' }
        format.json { render :show, status: :created, location: @place }
      else
        format.html { render :new }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /places/1
  # PATCH/PUT /places/1.json
  def update
    respond_to do |format|
      if @place.update(place_params)
        format.html { redirect_to @place, notice: 'Place was successfully updated.' }
        format.json { render :show, status: :ok, location: @place }
      else
        format.html { render :edit }
        format.json { render json: @place.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /places/1
  # DELETE /places/1.json
  def destroy
    @place.destroy
    respond_to do |format|
      format.html { redirect_to places_url, notice: 'Place was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_place
      @place = Place.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def place_params
      params.require(:place).permit(:name, :address, :latitude, :longitude)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/criminals_helper.rb
module CriminalsHelper
end

app/helpers/places_helper.rb
module PlacesHelper
end

app/views/criminals/_form.html.erb
<div class="wrapper">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <div class="card-box" style="margin-top: -120px;">
                            <%= form_with(model: criminal, local: true) do |form| %>
                              <% if criminal.errors.any? %>
                                <div id="error_explanation">
                                  <h2><%= pluralize(criminal.errors.count, "error") %> prohibited this criminal from being saved:</h2>

                                  <ul>
                                  <% criminal.errors.full_messages.each do |message| %>
                                    <li><%= message %></li>
                                  <% end %>
                                  </ul>
                                </div>
                              <% end %>
                            <div class="row">
                                <div class="col-lg-6">
                                        <div class="form-group">
                                          <%= form.label :first_name , class: 'col-md-2 control-label'%>
                                            <%= form.text_field :first_name, id: :criminal_first_name , class: 'form-control' %>
                                        </div>

                                        <div class="form-group">
                                          <%= form.label :second_name , class: 'col-md-2 control-label'%>
                                            <%= form.text_field :second_name, id: :criminal_second_name , class: 'form-control' %>
                                        </div>

                                        <div class="form-group">
                                          <%= form.label :identification_mark , class: 'col-md-2 control-label'%>
                                            <%= form.text_field :identification_mark, id: :criminal_identification_mark , class: 'form-control' %>
                                        </div>

                                        <div class="form-group">
                                          <%= form.label :location_of_crime , class: 'col-md-2 control-label'%>
                                            <%= form.text_area :location_of_crime, id: :criminal_location_of_crime , class: 'form-control' %>
                                        </div>

                                        <div class="form-group">
                                          <%= form.label :address , class: 'col-md-2 control-label'%>
                                            <%= form.text_area :address, id: :criminal_address , class: 'form-control' %>
                                        </div>
                                        
                                        <div class="form-group">
                                          <%= form.label :height , class: 'col-md-2 control-label'%>
                                            <%= form.number_field :height, id: :criminal_height , class: 'form-control'%>
                                        </div>

                                        <div class="form-group">
                                          <%= form.label :weight , class: 'col-md-2 control-label'%>
                                            <%= form.number_field :weight, id: :criminal_weight , class: 'form-control' %>
                                        </div>

                                        <div class="form-group">
                                          <%= form.label :description , class: 'col-md-2 control-label'%>
                                            <%= form.text_area :description, id: :criminal_description , class: 'form-control'%>
                                        </div>

                                        <div class="form-group">
                                          <%= form.label :gender , class: 'col-md-2 control-label'%>
                                            <%= form.text_field :gender, id: :criminal_gender , class: 'form-control' %>
                                        </div>

                                        <div class="form-group">
                                          <%= form.label :age , class: 'col-md-2 control-label'%>
                                            <%= form.number_field :age, id: :criminal_age, class: 'form-control' %>
                                        </div>

                                        <div class="form-group">
                                          <%= form.file_field :avatar %>
                                        </div>  

                                        <div class="form-group">
                                        <%= form.submit %>
                                      </div>
                                    <% end %>
                                </div><!-- end col -->

                            </div><!-- end row -->
                        </div>
                    </div><!-- end col -->
                </div>
                <!-- end row -->

app/views/criminals/edit.html.erb
<h1>Editing Criminal</h1>

<%= render 'form', criminal: @criminal %>

<%= link_to 'Show', @criminal %> |
<%= link_to 'Back', criminals_path %>

app/views/criminals/index.html.erb
<p id="notice"><%= notice %></p>
<% if user_signed_in? %>
  <%= link_to('Logout', destroy_user_session_path, method: :delete) %> 
  <h1> Welcome , <%= current_user.email %> </h1>       
<% else %>
  <%= link_to('Login', new_user_session_path)  %>
  <h1>You need to Login to be able to access</h1>  
<% end %>





<br><br>
<h1>Criminals Record</h1>

<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Second name</th>
      <th>Identification mark</th>
      <th>Location of crime</th>
      <th>Address</th>
      <th>Height</th>
      <th>Weight</th>
      <th>Description</th>
      <th>Gender</th>
      <th>Age</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @criminals.each do |criminal| %>
      <tr>
        <td><%= criminal.first_name %></td>
        <td><%= criminal.second_name %></td>
        <td><%= criminal.identification_mark %></td>
        <td><%= criminal.location_of_crime %></td>
        <td><%= criminal.address %></td>
        <td><%= criminal.height %></td>
        <td><%= criminal.weight %></td>
        <td><%= criminal.description %></td>
        <td><%= criminal.gender %></td>
        <td><%= criminal.age %></td>
        <td><%= image_tag criminal.avatar.url(:thumb) %></td>
        <td><%= link_to 'Show', criminal %></td>
        <td><%= link_to 'Edit', edit_criminal_path(criminal) %></td>
        <td><%= link_to 'Destroy', criminal, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Criminal', new_criminal_path %>

app/views/criminals/new.html.erb
<h1>New Criminal</h1>

<%= render 'form', criminal: @criminal %>

<%= link_to 'Back', criminals_path %>

app/views/criminals/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>First name:</strong>
  <%= @criminal.first_name %>
</p>

<p>
  <strong>Second name:</strong>
  <%= @criminal.second_name %>
</p>

<p>
  <strong>Identification mark:</strong>
  <%= @criminal.identification_mark %>
</p>

<p>
  <strong>Location of crime:</strong>
  <%= @criminal.location_of_crime %>
</p>

<p>
  <strong>Address:</strong>
  <%= @criminal.address %>
</p>

<p>
  <strong>Height:</strong>
  <%= @criminal.height %>
</p>

<p>
  <strong>Weight:</strong>
  <%= @criminal.weight %>
</p>

<p>
  <strong>Description:</strong>
  <%= @criminal.description %>
</p>

<p>
  <strong>Gender:</strong>
  <%= @criminal.gender %>
</p>
<p>
  <%= image_tag @criminal.avatar.url(:medium) %>
</p>

<p>
  <strong>Age:</strong>
  <%= @criminal.age %>
</p>

<%= link_to 'Edit', edit_criminal_path(@criminal) %> |
<%= link_to 'Back', criminals_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="">
  <title>Police</title>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <%= javascript_include_tag "https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js", "https://oss.maxcdn.com/respond/1.4.2/respond.min.js" %>
  <![endif]-->

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <p class="notice"><%= notice %></p>
       <p class="alert"><%= alert %></p>

            <!-- Navigation Bar-->
        <header id="topnav">
            <div class="topbar-main">
                <div class="container">

                    <!-- LOGO -->
                    <div class="topbar-left">
                        <a href="index.html" class="logo"><span>Criminal Records</span></span></a>
                    </div>
                    <!-- End Logo container-->



            
                    </div>
                </div>
            </div>
            
        </header>
  <div class="container">
    <% flash.each do |name, msg| %>
      <%= content_tag :div, class: "alert alert-#{ name == :error ? "danger" : "success" } alert-dismissable", role: "alert" do %>
        <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <%= msg %>
      <% end %>
    <% end %>

    <%= yield %>
  </div>
</body>
</html>

app/views/places/_form.html.erb
<%= form_with(model: place, local: true) do |form| %>
  <% if place.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(place.errors.count, "error") %> prohibited this place from being saved:</h2>

      <ul>
      <% place.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :place_name %>
  </div>

  <div class="field">
    <%= form.label :address %>
    <%= form.text_field :address, id: :place_address %>
  </div>

  <div class="field">
    <%= form.label :latitude %>
    <%= form.text_field :latitude, id: :place_latitude %>
  </div>

  <div class="field">
    <%= form.label :longitude %>
    <%= form.text_field :longitude, id: :place_longitude %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/places/edit.html.erb
<h1>Editing Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Show', @place %> |
<%= link_to 'Back', places_path %>

app/views/places/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Places</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Latitude</th>
      <th>Longitude</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @places.each do |place| %>
      <tr>
        <td><%= place.name %></td>
        <td><%= place.address %></td>
        <td><%= place.latitude %></td>
        <td><%= place.longitude %></td>
        <td><%= link_to 'Show', place %></td>
        <td><%= link_to 'Edit', edit_place_path(place) %></td>
        <td><%= link_to 'Destroy', place, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Place', new_place_path %>

app/views/places/new.html.erb
<h1>New Place</h1>

<%= render 'form', place: @place %>

<%= link_to 'Back', places_path %>

app/views/places/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @place.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @place.address %>
</p>

<p>
  <strong>Latitude:</strong>
  <%= @place.latitude %>
</p>

<p>
  <strong>Longitude:</strong>
  <%= @place.longitude %>
</p>

<%= link_to 'Edit', edit_place_path(@place) %> |
<%= link_to 'Back', places_path %>